#where to get the data f
#where to store the data

parent_folder: 
  artifacts_root: artifacts

data_ingestion:
  inner_folder: artifacts/data_ingestion
  path_to_csv: C:/Users/User/Downloads/PROJECTS/newproject/notebook/data/stud.csv
  data_store: artifacts/data_ingestion/student_performance.csv

data_transformation:
  inner_folder : artifacts/data_transformation
  raw_data: artifacts/data_ingestion/student_performance.csv
  transformed_train_set: train.csv
  transformed_test_set: test.csv

model_trainer :
  train_csv: artifacts/data_transformation/train.csv
  test_csv: artifacts/data_transformation/test.csv
  model_file_innerfolder : artifacts/model_trainer   #need some where to store my model pickle file that i will use in prediction pipeline
  model_file_path : model.pkl
  report_file_path : report.yaml #need some where to store my report pickle file
