categorical: 
    gender   :                      str
    race_ethnicity:                  str
    parental_level_of_education   :  str
    lunch   :                        str
    test_preparation_course :         
    
numerical:
    
    reading_score :                  int 
    writing_score :                  int 

Target_column1:
    math_score   :                   int 

Target_column2:
    reading_score:                    int

Target_column3:
    writing_score:                     int


